# NOTE: update this with your service name
service: serverless-nodejs-starter

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    port: 5000

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment: ${file(env.yml):${self:provider.stage}}

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
  graphql:
    handler: src/graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
  neo4j:
    handler: src/neo4j/neo4j.neo4jHandler
    events:
      - http:
          path: neo4j
          method: post

